#Stage 1
FROM stefanscherer/node-windows

COPY /LSP /LSP

WORKDIR /LSP


RUN npm install -g @angular/cli@latest

RUN npm install

RUN $(npm bin)/ng build

#Stage 2 
FROM nginx
COPY --from=builder /LSP/dist/*     /usr/share/nginx/html/

EXPOSE 80